# Get Conversion Status by Job ID

# Description

Retrieve the conversion status of the Convert Speech to Text Asynchronously activity.

# Project compatibility

Windows | Cross-platform

# Configuration

* 
* Job ID - The job ID output generated by .





* Status - The current state of the job, such as success, failure, or pending. Automatically generated output variable.
