# Temporary registry installation fails on RHEL 8.9

# Description

When installing a temporary registry on RHEL 8.9, you might encounter an issue that causes the process to fail. This issue occurs due to the deprecated systemd generate command in Podman and the absence of secontext in the systemd files generated by Podman. These conditions prevent systemd from accessing the necessary files, leading to an unsuccessful installation.

# Solution

To fix this issue, you must start the container registry by taking the following steps:

1. Adjust the security context:chcon -u unconfined_u -r object_r -t systemd_unit_file_t /etc/systemd/system/container-registry-tmp.service
2. Reload the systemd manager configuration:systemctl daemon-reload
3. Enable the registry service:systemctl enable container-registry-tmp.service
4. Start the registry service:systemctl start container-registry-tmp.service

After starting the container registry using these steps, you do not have to retry the registry installation command.
