# Generate Text Completion

UiPath.AnthropicClaude.IntegrationService.Activities.GenerateTextCompletion

# Description

Generates a text completion response based on a given prompt.

# Project Compatibility

Windows | Cross-platform

# Configuration

ConnectionId - The
                        connection established in Integration Service. Access the drop-down to
                        choose, add or manage connections.Model - The model that you want to use for generating text.Prompt - The prompt
                        you want Claude to use for the generation of the text completion.Max Tokens - The
                        maximum number of tokens allowed for the prompt and generated answer.
                        Maximum value for this field is 100,000. Default value is
                            256.

# Advanced

Options

* Temperature - The amount of randomness you want to inject into the response. Accepted values are between 0 and 1.
* Top P - A number between 0 and 1. The lower the number, the fewer tokens are considered. Defaults to 0.7.
* Top K - Used to remove "long tail" low probability responses. Only sample from the top K options for each subsequent token.

Output

* Response - The text completion object returned.
* Top generated text -The text for the top choice generated by AI.
