# About Selectors

To automate specific actions in the user interface, you are required to interact with various windows, buttons, drop-down lists and many others. One of the ways in which UI elements can be identified is by using their position on the screen, but this can be unreliable.

To overcome this problem, Studio uses what we call selectors. These store the attributes of a
            graphical user interface element and its parents, in the shape of an XML fragment.

Most of the times, selectors are automatically generated by Studio and do not require further input from you, especially if the apps you are trying to automate have a static user interface.

However, some software programs have changing layouts and attribute nodes with volatile values,
            such as some web-apps. Studio cannot predict these changes and, therefore, you might
            have to manually generate some selectors.

A selector has the following structure:

<node_1/><node_2/>...<node_N/>

The last node represents the GUI element that interests you, and all the previous ones represent the parents of that element. <node_1> is usually referred to as a root node, and represents the top window of the app.

Each node has one or more attributes that help you correctly identify a specific level of the selected application.

Each node has the following format:

<ui_system attr_name_1='attr_value_1' ... attr_name_N='attr_value_N'/>

Every attribute has an assigned value. It is important to pick attributes with a constant value. If the value of an attribute changes each time the app is started, then the selector will not be able to correctly identify the element.

Selectors are displayed in the Properties panel of activities, under Input > Target
                > Selector. All activities related to graphical elements have this
            property.

![271685c-184=GUID-28281215-122B-41A0-AE4A-350D774DEB28=1=en=Default](/images/271685c-184=GUID-28281215-122B-41A0-AE4A-350D774DEB28=1=en=Default.png)

The Selection Options window enables you to select and edit a target. To access this
            window, in the Workflow Designer panel, click the Options  button in the body of
            an activity and select Indicate target on screen or  Edit target.

![uia_selection_screen_target_no_anchor=GUID-5C1CABE8-D899-4C38-8A14-7C3499DA485F=1=en=Default](/images/uia_selection_screen_target_no_anchor=GUID-5C1CABE8-D899-4C38-8A14-7C3499DA485F=1=en=Default.png)

The Selector Editor window enables you to see the automatically-generated selector
            and edit it and its attributes. To access this window, use the Ellipsis  button next to the
                Selector field, in the Properties panel.

![4335ceb-selector_editor1=GUID-51F0C057-1D8D-47BA-BBCB-5B170700B0AC=1=en=Default](/images/4335ceb-selector_editor1=GUID-51F0C057-1D8D-47BA-BBCB-5B170700B0AC=1=en=Default.png)


| Option | Description |
| --- ---| Validate | The button shows the status of the selector by checking the validity of the selector definition and the visibility of the target element on the screen.The Validate button has three states: Selector is being validated Valid selector Invalid selector Modified selector, revalidateThe button is correlated with UI Explorer validation states. |
| Indicate Element | Indicate a new UI element to replace the previous one. |
| Repair | Enables you to re-indicate the same target UI element and repair the selector. This operation does not completely replace the previous selector. The button is available only when the selector is invalid. |
| Highlight | Brings the target element in the foreground. The highlight stays on until the option is disabled with a click. The button is enabled only if the selector is valid. |
| Edit Attributes | Contains all the application components needed to identify the target application (a window, a button etc.). This section is editable. |
| Edit Selector | Holds the actual selector. This section is editable. |
| Open in UI Explorer | Launches the UI Explorer. The option is enabled only for valid selectors. |

In some situations, when Studio and the targeted application are opened with different elevated privileges, the selector might not work. We recommend to always open both applications with the same privileges.

## Supported Tags and Attributes

The following tables present the compatibility between tags and attributes used to build selectors and the selector capability:

Selectors generated for Java applications which contain multiple WND tags cannot be used with events monitoring.

# WND

AttributeFuzzyRegExCase-Sensitiveappclstitleaanamectrlname (WinForms)ctrlid (WinForms)idxtidpidisremoteappaastatesapClient (SAP)sapLanguage (SAP)sapProgram (SAP)sapScreen (SAP)sapSession (SAP)sapSysName (SAP)sapSysNumber (SAP)sapSysSessionId (SAP)sapTransaction (SAP)sapUser (SAP)

# HTML

AttributeFuzzyRegExCase-Sensitiveurlhtmlwindownametitleclassappidxpidtidexcludehwndbsid (Browser Session ID)isremoteapp

# WEBCTRL

The tag and idx attributes use string values. All other WEBCTRL attributes have dynamic values.

AttributeFuzzyRegExCase-Sensitivetagidxaanamenameidparentidclasscss-selectorinnertextvisibleinnertextisleafparentclassparentnamesrchreftableColtableRowcolNamerowNamearia-labelaria-labelledby

# CTRL

AttributeFuzzyRegExCase-SensitiverolenameautomationidlabeledbyaastatevirtualnametextrowNameidx

# UIA

AttributeFuzzyRegExCase-Sensitiveaccelkey (Accelerator Key)acskey (Access Key)automationidclshelpTextlegacyAccHelp (Legacy Accessible Help)enabledkbfocus (Is Keyboard Focusable)ispwd (Is Password)itemstatusitemtypertid (Runtime ID)rolenamepidtableRowtableColrowNamecolNameidx

# JAVA

AttributeFuzzyRegExCase-SensitiverolenamevirtualnamejavastatetableRowtableColrowNamecolNameidx

# SAP

AttributeFuzzyRegExCase-SensitiveidleafidThis attribute is not exposed in the Attribute panel because it is mutual-exclusive with the id attribute. It can be added manually.tableRowtableColcolNamerelpathitemId

# SILVERLIGHT

Please note that the Silverlight tag does not support Fuzzy, RegEx, and Case-Sensitive capabilities.

