# About Automation Cloud Dedicated

{Delivery option} is a cloud-based enterprise SaaS solution tailored to the specific requirements of large organizations. Our platform helps you manage all your automation work and resources in one place. It is designed to provide you with a frictionless startup experience, streamlined collaboration, effortless scalability, and instant access to new functionalities.

Large organizations have specific requirements that demand robust, secure, and compliant software solutions. These organizations handle vast amounts of sensitive data, from banking information to financial transactions, making data security and privacy paramount.

## Key benefits

* Dedicated compute and data resources - As a single-tenant SaaS solution, it provides infrastructure-level isolation of your environment.
* Upgrade controls - You have flexibility around upgrades: Delay - You can delay updates up to 30 days.Blackout - We ensure no updates are rolled out for a specific period of time with a blackout window up to 30 days.
* Data encryption: We employ FIPS 140-2 validated encryption for data at rest and in transit, ensuring the highest level of data protection.
* TLS protocol: Our software uses TLS 1.2 or higher to secure data transmissions, guaranteeing the confidentiality of your information during transit.
* Customized URL endpoint - You can choose the fully qualified domain name for your dedicated instance.
* Data residency -{Delivery option} is deployed on Azure in a cloud region of your choice.
* Advanced connectivity option - You can allow traffic between the dedicated instance and your environment without exposing data to the internet or simplify restrict with your CIDR ranges.


## Product and service offering

The UiPath platform consists of various products designed to automate processes, enhance collaboration, and drive operational efficiency:

* Action Center UiPath Action Center is a tool designed to help you manage and resolve exceptions, errors, or decisions that require human intervention in your automation workflows. It provides a central interface for handling these exceptions, allowing human workers to review, make decisions, and take actions as needed to ensure the successful completion of automated processes. Visit the Action Center documentation.
* Agents UiPath Agents is a low-code development environment to build, evaluate, and publish enterprise Agents. It provides all of the necessary elements to create an agent which uses a large language model to interpret a natural language prompt, retrieve relevant context, call UiPath tools, and bring in humans as necessary to review output. Visit the Agents documentation.
* AI Center UiPath AI Center is a service that allows you to deploy, manage, and continuously improve Machine Learning models and consume them within RPA workflows in Studio. Visit the AI Center documentation.
* AI Computer Vision UiPath AI Computer Vision is a machine-learning based method used to visually identify all the UI elements on a computer screen and interact with them via UiPath Robots, simulating human interaction. It does not require or use the underlying properties of applications, but only the aspect and relationship of various screen elements. Visit the AI Computer Vision documentation.
* Apps UiPath Apps is a low-code application development platform that enables you to build and share enterprise-grade custom applications that deliver engaging user experiences. Using Apps, you can quickly build custom business applications that connect to data in any underlying cloud or on-premises system using the power of automation. Visit the Apps documentation.
* Automation Cloud Robots - Serverless UiPath Automation Cloud Robots - Serverless make it easy to run background automation without worrying about the necessary infrastructure. They provide you with complete freedom from provisioning, managing, maintaining, and scaling any underlying infrastructure. UiPath handles all the work behind the scenes so you do not have to deal with containers, virtual machines, or physical servers. Visit the Automation Cloud Robots - Serverless documentation.
* Automation Cloud Robots - VM UiPath Automation Cloud Robots - VM is a hassle-free solution that streamlines the process of setting up the necessary infrastructure for running automations. It provides ready-to-use virtual machines where you can run automations. You just need to configure the virtual machine based on your need, and it is all set to run your tasks. Visit the Automation Cloud Robots - VM documentation.
* Automation Hub UiPath Automation Hub is a collaborative process identification, automation pipeline management, and process repository tool. Its goal is to accelerate the adoption of RPA across your organization, by building an RPA Community of Interest. Visit the Automation Hub documentation.
* Automation Ops UiPath Automation Ops is a tool that enables you to manage and implement governance policies based on user profiles, and to manage the feeds available in your organization. Visit the Automation Ops documentation.
* Communications Mining Communications Mining, or Comms Mining, is a field that focuses on understanding and extracting value from communications data. It is the practice of converting the unstructured information this data contains into structured, machine-readable data that can then be used for analytics and automation. Visit the Communications Mining documentation.
* Data Service UiPath Data Service is a persistent data storage service that brings no-code data modeling and storage capabilities to your automation projects. Visit the Data Service documentation.
* Document Understanding UiPath Document Understanding uses pre-defined solutions to extract and categorize data from common document types. Utilizing pre-trained models, it can pull information from standard documents with ease. Visit the Document Understanding documentation.
* Insights UiPath Insights is a tool that serves as a platform for data modeling and analytics using a combination of available business metrics and operational insights into your automations and robot performance. Visit the Insights documentation.
* Integration Service UiPath Integration Service is the component of the UiPath Platform that makes the automation of third-party applications much easier by standardizing authorization and authentication, helping you manage API connections, and also allowing faster integration into SaaS platforms. By using prebuilt APIs, the development of automation projects in UiPath Studio is more simple and more consistent, regardless of the third-party applications you are automating. Visit the Integration Service documentation.

* Maestro UiPath Maestro combines robotic and agentic workflows to seamlessly integrate human, AI, and robotic interactions, driving hyper-efficient business processes. With its robust capabilities, Maestro empowers businesses to optimize their operations at scale while simplifying complex workflows. Visit the Maestro documentation.
* Orchestrator UiPath Orchestrator is a tool for streamlining the deployment, monitoring, and governance of your automation processes and robots, giving you flexibility to schedule and trigger these processes as per your requirements. It also supports the management of transactional data, often used in automating business processes. Visit the Orchestrator documentation.
* Process Mining UiPath Process Mining is a process mining solution that transforms data from your IT systems into visual interactive dashboards, allowing you to view existing value decreases, bottlenecks, and discrepancies, as well as understanding the root-causes and possible risks. It offers real-time, valuable insights to improve business processes over time. Visit the Process Mining documentation.
* Solutions Management UiPath Solutions Management provides an out-of-the-box means to manage the lifecycle of your solutions, once built. This set of capabilities comes into play once you are done developing your solutions, and you want to promote them to a new environment. Visit the Solutions Management documentation.
* Studio Web UiPath Studio Web enables you to build and test cross-platform automations across online business apps and services. All you need to start using Studio Web is a web browser. You can access it from any operating system, it requires no installation, it has no IT dependencies, and it is always up to date. Visit the Studio Web documentation.
* Task Mining UiPath Task Mining offers insights into ongoing processes on your team's desktops, uncovering potential areas for automation and process improvement. This tool logs desktop data for each user action and uses AI to analyze it, thereby, giving you actionable insights for identifying automation ideas. Visit the Task Mining documentation.
* Test Manager UiPath Test Manager is a test management tool for enterprise testing. It integrates into your ecosystem and adapts to your way of working, whether you use ServiceNow, SAP Solution Manager, Jira, Azure DevOps. Visit the Test Manager documentation.

We are currently in the process of onboarding several other products. Stay tuned.

