# Applications and technologies automated with
    UI Automation 

The tables in this section present the applications and technologies which can be automated
      using the UiPath.UIAutomation.Activities (UIA) package by indicating the minimum
      required UI Automation package/ Studio version. It also presents the improvements added in
      later versions for that application/ technology and the prerequisites for using it.

## Web browsers

Application/ TechnologyMinimum required UIA package/ Studio versionImprovements added in later versionsPrerequisitesChromeStudio v2016.2The UiPath Extension for Chrome MV3 is available starting with Studio versions 2022.4.1, 2021.10.8, 2020.10.14, 2019.10.9. Also available in all 2022.10 and 2023.4 versions.UIA v19.7.0 - The Chrome Extension can also be installed on Chrome versions lower than v64.UIA v20.4.1 - The Extension for Chrome can be installed using Policy settings.UIA v21.4.3 - Added support for websites that use Shadow DOM for their UI elements.UIA v21.10.3 - ChromiumAPI input method has been implemented.Starting with Studio v2022.4 the UiPath Extension for Chrome can be used to automate Chrome Apps.UIA v22.4.4 - The new Extension for Chrome is also available on Mac.Extension for Chrome must be installed.Edge (Chromium)Studio v2019.10.5 (UIA v19.11.3)The UiPath Extension for Edge MV3 is available starting with Studio versions 2022.4.4, 2021.10.8, 2020.10.14, 2019.10.9.UIA v20.10.5 - Added support for Edge IE Mode.UIA v21.10.3 - The Edge Extension supports Java Applets and ActiveX controls in IE Mode.UIA v21.4.3 - Added support for websites that use Shadow DOM for their UI elements.UIA v21.10.3 - ChromiumAPI input method has been implemented.Starting with Studio v2022.4 the UiPath Extension for Edge can be used to automate Edge Apps.Windows 10 version 1803 or higherMicrosoft Edge Chromium version 79 or higherExtension for Edge must be installed.FirefoxStudio v2016.2UIA v21.4.3 - Added support for websites that use Shadow DOM for their UI elements.Mozilla Firefox v52.0 or higherExtension for Firefox must be installed.Internet ExplorerStudio v2016.2N/AInternet Explorer v8.0 or higherWebDriverUIA v19.10.1UIA v19.10.1 - The WebDriver protocol can only be used with Google Chrome and Mozilla Firefox.UIA v20.4.1 - Added WebDriver protocol support for Microsoft Edge Chromium browser.UIA v21.10.1 - Cross-origin IFRAME support via WebDriver.Depending on the web browser, one of the following must be installed on the client machine:ChromeDriverChromeDriver.exeMicrosoft Edge Drivermsedgedriver.exegeckodrivergeckodriver.exe


## Web embedding frameworks

Application/ TechnologyMinimum required UIA package/ Studio versionImprovements added in later versionsPrerequisitesJxBrowserUIA v19.3.0UIA v19.5.0 - Screen and Data Scraping can be used to create automation projects for applications relying on the JxBrowser library.N/ACefSharpUIA v19.8.0-ceUIA v21.10.3 - UI elements from CefSharp embedded widgets (e.g. SharpBrowser, SAP NWBC with Fiori Launchpad) are recognized as belonging to the host application instance.N/AWebView2UIA v22.4.3Embedded Edge support


## Virtualization technologies

Application/ TechnologyMinimum required UIA package/ Studio versionImprovements added in later versionsPrerequisitesCitrixUIA v18.4.2 - Native support for Citrix XenAppsUIA v19.4.1 - You can create browser automations with native selectors for web applications exposed through Citrix Virtual Apps and Desktops.UIA v22.4.4 - Supports automating in nested CitrixApps.Virtual App v6.5 or higherVirtual Desktop v7.0 or higherExtension for Citrix must be installed on the client machine.UiPath Remote Runtime component must be deployed on all Citrix Application servers.Microsoft Remote Desktop and AppsUIA v19.4.1UIA v20.10.12, UIA v21.10.5, UIA v22.4.3 – Added support for Azure Windows Virtual Desktop client (msrdc.exe).UIA 21.10.3 - Applications provisioned through Microsoft RemoteApp can be automated.Requires a RDP client that uses mstsc.exe.Extension or Microsoft Remote Desktop and Apps must be installed on the client machine.UiPath Remote Runtime component must be deployed on the Remote Desktop machine.Microsoft App-VUIA v19.6.0Support for web and native applications exposed through the Microsoft App-V virtualization technology.The UiPath Extensions for the underlying technology must be installed and requires a few extra steps (browsers extensions or Java extension; details in Microsoft App-V Support and Limitations).VMware HorizonUIA v20.4.1N/AExtension for VMware Horizon must be installed on the client machine.UiPath Remote Runtime component must be deployed on all VMware Application servers.


## ERP applications

Application/ TechnologyMinimum required UIA package/ Studio versionImprovements added in later versionsPrerequisitesSAP WinGUIUIA v20.4.1N/ASAP WinGUI for Windows 7.40 or higherSAP WebGUIUIA v22.12.0-previewN/ASAP WebGUISAP FioriUIA v20.10.5N/ASAP Fiori versions 1.52 and above, which are in Maintenance by SAP.SalesforceUIA v21.10.3Salesforce Lightning, with specific Salesforce AURA components path and attributes, and reliable selectors, is now supported in Chrome and Edge.Salesforce UI automation can be created on the following web browsers:Microsoft Edge - requires the Extension for Edge.Google Chrome - requires the Extension for Chrome.


## Application framework

Application/ TechnologyMinimum required UIA package/ Studio versionImprovements added in later versionsPrerequisitesSilverlightStudio v2018.1 (UIA v18.2)N/ARequires Silverlight Developer Runtime version 5.1.50918.0.Extension for Silverlight must be installed.JavaStudio v2018.1 (UIA v18.2)UIA v19.7.0 - Added the possibility to create automation projects for OpenJDK.UIA v19.8.0-ce - Selectors for the NetPhantom framework are now natively generated.UIA 22.2 - The injection mechanism has become more reliable and is able to automate applications like .jnlp applications launched with third party applications, like OWS or IcedTea Web.UIA v22.4.4 - Java versions 16 and 17 are now officially supported.UIA v22.4.4 - Improved support for Java Konsis and the custom Java Framework McBeans.The Java Extension is compatible with any version of JRE's, from Java 3 to Java 17.Extension for Java must be installed.WinFormsUIA v2016.2Automated with the Active Accessibility framework.N/AWin32UIA v2016.2Automated with the Active Accessibility framework.N/AWPFUIA v2016.2Automated with the Active Accessibility framework.N/AVB6/EpicUIA v22.10.2UIA v22.10.2 - Better VB6/Epic attributes: ctrlid and automationid attributes.N/AQtUIA v22.10.2UIA v22.10.2 - Support for applications based on the Qt Framework through the new type of selector tag: qt.For now, only widgets are supported. No QtQuick/QML support available at the moment.N/A

