# Application Event Trigger

UiPath.UIAutomationNext.Activities.NNativeEventTrigger

# Description

Sets up a trigger based on a native event of any type of element (top-level window or any other indicated UI element). You can indicate the target element on screen and then choose the native event from the list of events supported by that element.



The trigger must be the first activity in the workflow and the workflow is triggered when a certain UI event occurs. Only one trigger per workflow is allowed. For more details, check out Trigger-based Attended Automation.

If you are using a Studio version lower than 2023.4, you need to place the Application Event Trigger activity inside a Trigger Scope activity. In this case, the Application Event Trigger activity does not display the Scheduling mode and Enabled properties and the Scheduling mode property is available in the Trigger Scope activity.

# 

|

# 



* Click Indicate target on screen to indicate the UI element to use as target.
* Event type - The list of native event types specific to the indicated element. The event type must be set. The exposed events list is dependent on the target element type and on the target application technology. For example, a web UI element might expose a different list of events than a Java UI element.









* Match sync - Indicates whether the matching of the target element selector is done synchronously or asynchronously. It is supported only for Java events except for Appeared and Disappeared. This field supports only Boolean values. The default value is False.
* Selectors - Optional collection of selectors to monitor for the indicated event; these selectors are monitored alongside the indicated target. The selectors must be full (not partial) selectors.

* Target - The target element: top-level window or UI element. Only strict selectors are supported, without anchors. Target element must be set. Before indicating on screen, this field is set to (null). Once the target is indicated, all properties regarding the element that was indicated are displayed.Strict selector - The strict selector generated for the target UI element. It is empty for top-level windows.Window selector (Application instance) - The selector for the application window (application/browser).



* Enabled - If set to False, the trigger starts but does not fire any events. It can be enabled later at runtime, by using the Enable Local Trigger activity. This property is hidden when the Application Event Trigger activity is placed inside a Trigger Scope. This field supports only Boolean values. The default value is True.
* 



* Include children - When selected, the children of the specified UI element are also monitored. It supports all event types except for Appeared or Disappeared and any UI element except for top-level windows. This field supports only Boolean (True, False) values. The default value is False.
*

### Native events




### Event Inspection Tool

In the context of trigger-based attended automation, the Event Inspection Tool can
            be used to identify the type of native events triggered when you interact with certain
            UI elements in an application, and then it can be used for configuring the
            Application Event Trigger activity. The tool captures and monitors all the
            selected event types, such as Click, Key pressed, Focus gained,
            Focus lost, and other relevant interactions, enabling you to analyze the
            actions performed and, if applicable, diagnose issues.

The Event Inspection Tool can be opened from the UI Explorer, once a valid
            UI element is selected, by clicking the Inspect Events toolbar button.



The toolbar consists of the following options:Record - The events
                generated by interacting with the UI element are recorded and added to the
                events list.Pause - The events generated by the UI element when you interact with it
                are no longer recorded.Highlight - Shows the contour
                of the target element and brings it to the foreground for a few seconds. The
                highlight stays on until it is disabled.Open in UI Explorer - The
                monitored element is opened in UI Explorer where you can observe the selector of
                that element.

Once you start event recording, two more options become available:Clear - Deletes all the recorded events.CSV - The captured events can be exported to a .csv file
                for further analysis.

The Event Inspection Tool window has two main sections:Event filter - Allows selecting the types of events you want to monitor for the
                target element.Event list - Displays information about captured events.

You can filter event types to be captured by enabling or disabling the checkboxes from
            the list of event types. The list may vary based on the selected element technology.

All mouse event types (Mouse move, Mouse pressed, Mouse released,
            Mouse entered, Mouse exited), specific for Web or Java UI elements,
            are disabled by default because the event list, in such cases, can become quite large.
            Our recommendation is to enable the mouse event types only if you have a specific need
            to monitor them.

It is worth also mentioning that event types can be enabled or disabled even after you
            started the event recording.

The event list has three columns:Event Name - The event
                type.Time Stamp - The date and
                hour when the event was performed.Event Data - The
                associated data and parameters for a certain event.Each column can be sorted in ascending or descending order. The events are
            displayed by default in the order they were performed.



When the Disappeared event type is found, you can no longer continue monitoring
            and an error message is displayed on the screen. When clicking any option from the
            toolbar, the same error message is displayed on the screen. The only available options
            are to either clear the data or export it to a .csv file. To start
            monitoring again, close the window and open another instance of the Event Inspection
                Tool.

