# Roles and policies

The the following table describes the IAM roles and policies that the CloudFormation template creates:


| Role | Actions |
| --- ---| CopyRoleThis role is used to copy objects between S3 buckets. It is a copy of the  AWS repository initially used for the AWS QuickStart.File: copy-zips.template.yaml | s3:GetObjects3:PutObjects3:DeleteObject |
| ACMCertificateRoleThe purpose of this role is to create and verify an ACM certificate using DNS validation and Route 53. It is a copy of the  AWS repository used for the AWS QuickStart.File: quickstart-aws-acm-certificate.template.yml | acm:RequestCertificateacm:DescribeCertificateacm:DeleteCertificateroute53:ChangeResourceRecordSets |
| VPCFlowLogsRoleThis role serves as the value of the DeliverLogsPermissionArn parameter in the AWS::EC2::FlowLog resource type. Is it a copy of the  QuickStart repository.File: aws-vpc.template.yaml | logs:CreateLogStreamlogs:PutLogEventslogs:DescribeLogGroupslogs:DescribeLogStreams |
| AutomationAssumeRoleThis role is used for various SSM documents (AWS::SSM::Document), with the following purposes:AgentRemoveInstanceDocument: remove the agent instance from the cluster;ServerRemoveInstanceDocument: remove the server instance from the cluster;RegisterAiCenter: register the AI Center service to Orchestrator;OnDemandBackup: create a snapshot of the Automation Suite cluster;OnDemandRestoreDocument: restore the Automation Suite cluster from a given snapshot;GetBackupList: get the list of avaliable snapshots of the Automation Suite cluster;UpdateAMIDocument: update AMI for the scalling groups.AutomationAssumeRole allows full access to Amazon SSN. For more information, see AmazonSSMFullAccess.File: ec2-management.template.yaml | autoscaling:CompleteLifecycleActionautoscaling:RecordLifecycleActionHeartbeatautoscaling:UpdateAutoScalingGroupssm:SendCommandautoscaling:DescribeAutoScalingGroupsssm:PutParameterssm:GetParameterlogs:PutLogEventslogs:DescribeLogStreamslogs:DescribeLogGroupslogs:CreateLogStreamlogs:CreateLogGroupec2:DescribeImagesec2:DescribeLaunchTemplatesec2:DescribeLaunchTemplateVersionsiam:PassRoleec2:CreateLaunchTemplateVersionec2:RunInstancesstates:StartExecutionstates:DescribeExecution |
| StateMachinesAssumeRoleThis role is used for the OnDemandRestoreStateMachine resource (AWS::StepFunctions::StateMachine). This resource is used for the restore operation.StateMachinesAssumeRole allows full access to Amazon SSN. For more information, see AmazonSSMFullAccess.File: ec2-management.template.yaml | Uses the AmazonSSMFullAccessmanaged policy. |
| EventsBridgeAssumeRoleThis role is used for the following event rules (AWS::Events::Rule):AsRobotsTerminateEventRuleAgentTerminateEventRuleServerTerminateEventRuleThe rules are for the terminate lifecycle action.File: ec2-management.template.yaml | ssm:StartautomationExecutioniam:PassRole |
| ObjectStorageBucketsCleanupLambdaRoleThis role is used for the ObjectStorageBucketsCleanupFunction lambda function and provides utility for the object storage.File: external-storage.template.yaml | s3:GetAccelerateConfigurations3:GetBucketLocations3:GetBucketVersionings3:ListBuckets3:ListBucketVersionss3:ListBucketMultipartUploadss3:DeleteObjects3:DeleteObjectVersionlogs:CreateLogGrouplogs:CreateLogStreamlogs:PutLogEventsxray:PutTraceSegments |
| ServiceFabricIamRoleThis role is referenced in the following resources:ServiceFabricInstanceProfile (AWS::IAM::InstanceProfile)The following policies (AWS::IAM::Policy): LogsAccessPolicy, LifecycleHookActionsPolicy, Ec2QueryPolicy, QuickstartS3IAMPolicy, InputJsonSecretPolicy, KubeconfigSecretPolicy, InstallerDownloadUrlParameterPolicy, ExternalStorageAccessPolicy.File: uipath-sf.template.yaml | Uses the AmazonSSMManagedInstanceCore managed policy. |
| AsgProcessModificationRoleThis role is used to modify the ASG processes during CF stack creation.File: uipath-sf.template.yaml | autoscaling:ResumeProcessesautoscaling:SuspendProcesseslogs:CreateLogGrouplogs:CreateLogStreamlogs:PutLogEvents |
| FindAmiLambdaRoleThis role is used by the FindAMIFunction lambda function.File: uipath-sf.template.yaml | ec2:DescribeImageslogs:CreateLogGrouplogs:CreateLogStreamlogs:PutLogEventsxray:PutTraceSegments |
| CreateInputJsonLambdaRoleThis role is used by the CreateInputJsonFunction lambda function. The function creates the configuration file for the Automation Suite installation.File: uipath-sf.template.yaml | secretsmanager:GetSecretValuesecretsmanager:PutSecretValueautoscaling:DescribeAutoScalingGroupsautoscaling:DescribeAutoScalingInstanceslogs:CreateLogGrouplogs:CreateLogStreamlogs:PutLogEventsxray:PutTraceSegmentsec2:DescribeImagesec2:DescribeInstanceTypesec2:DescribeInstanceTypeOfferings |
| ComputeResourceSizeLambdaRoleThis role is used by the ComputeResourceSizeFunction lambda function. The function validates that the input for resources is in accordance with the hardware requirements.File: uipath-sf.template.yaml | autoscaling:DescribeAutoScalingGroupsautoscaling:DescribeAutoScalingInstancesec2:DescribeInstancesec2:DescribeInstanceTypeOfferingsec2:DescribeInstanceTypesec2:DescribeImagesec2:RunInstancesec2:CreateTagscloudformation:DescribeStackslogs:CreateLogGrouplogs:CreateLogStreamlogs:PutLogEventsxray:PutTraceSegments |




| Policy | Actions |
| --- ---| LogsAccessPolicyPolicy for log access. | logs:PutLogEventslogs:DescribeLogStreamslogs:DescribeLogGroupslogs:CreateLogStreamlogs:CreateLogGroupcloudwatch:PutMetricDataxray:PutTraceSegments |
| LifecycleHookActionsPolicyPolicy for lifecycle hook access. | autoscaling:CompleteLifecycleAction |
| Ec2QueryPolicyPolicy for EC2 and ASG access. | ec2:DescribeVolumesec2:DescribeTagsec2:DescribeInstancesautoscaling:DescribeAutoScalingInstancesautoscaling:DescribeAutoScalingGroupsec2:DescribeImagesec2:DescribeInstanceTypesec2:DescribeInstanceTypeOfferings |
| QuickstartS3IAMPolicyPolicy for getting access to the QS S3 bucket. | s3:GetObject |
| InputJsonSecretPolicyPolicy for allowing access to the secret manager. | secretsmanager:GetSecretValuesecretsmanager:PutSecretValue |
| KubeconfigSecretPolicyPolicy for allowing access to the secret manager. | secretsmanager:GetSecretValuesecretsmanager:PutSecretValue |
| InstallerDownloadUrlParameterPolicyPolicy for allowing access to SSM parameters. | ssm:GetParameter |
| ExternalStorageAccessPolicyPolicy for allowing access to external storage. | s3:GetBucketAcls3:GetBucketCORSs3:GetBucketLocations3:GetBucketNotifications3:GetBucketPolicys3:PutBucketPolicys3:DeleteBucketPolicys3:GetBucketVersionings3:ListBuckets3:ListBucketMultipartUploadss3:PutBucketAcls3:PutBucketCORSs3:*Objects3:*ObjectAcls3:*ObjectAttributess3:*ObjectVersions3:*ObjectVersionTaggings3:AbortMultipartUploads3:ListMultipartUploadPartss3:ListAllMyBuckets |
