# Bulk Form Designer

The Bulk Form Designer is a specialized Form Designer, allowing you to create forms that
            can be edited or completed in bulk. When you bulk edit actions, Action Center only
            modifies fields and data that are included in the Bulk Form Designer layout.

To open the Bulk Form Designer, select Open Bulk Form Designer in the body of the Create Form Task activity.

![b78a2b1-AC_enable_bulk_edit=GUID-5A45400F-CEC3-4419-8607-B840BFF04B00=1=en=Default](/images/b78a2b1-AC_enable_bulk_edit=GUID-5A45400F-CEC3-4419-8607-B840BFF04B00=1=en=Default.jpg)

Prerequisites

* Install UiPath.Persistence.Activities v1.3.0 or higher.
* Select the Enable Bulk Edit checkbox in the activity properties panel.

Components

The Bulk Form Designer has the same components as a classic Form Designer.

The difference it brings is that you can select specific components to be bulk edited.

# Workflow

The following steps demonstrate how to design a form that can be bulk-edited or completed:

1. While building the workflow, create a classic form to include all the components you need and save it.
2. Select the Enable Bulk Edit checkbox and click Open Bulk Form Designer. The Bulk Form Designer window opens.
3. Include only the form components that you want your users to bulk edit.Say your classic form has the following fields:Invoice Amount Discount Accountant NameYou can allow your users to bulk edit only the Discount and Accountant Name fields. Therefore, you add only those components in the Bulk Form Designer.
4. To allow bulk completion, add a Button component, to trigger the completion of the action (such as a Submit button).
5. Save your bulk form.
6. Publish the workflow to the corresponding Orchestrator tenant.
7. Create a process from the previously published version.
8. Start a job using the previously generated process to generate the actions.
9. Navigate to the Action tab of the corresponding Action Center instance and follow the steps documented here and here.Bulk editing is available only for actions with the same bulk form layout. You can bulk edit actions generated by different process versions only if the bulk form layout has not been modified between versions.
