# Manual Recording

As explained in the About Recording Types chapter, there are some actions that cannot be handled by the automatic recorder. We refer to these as single actions or manual recordings. You can use both manual and automatic recording in automations to achieve full automation of a task. Single actions can be found in the Actions group of any recording toolbar.

It is recommended to run your web automations on Internet Explorer 11 and above, Mozilla Firefox 50 or above, or the latest version of Google Chrome.

# Start and Stop an App or Browser

![e2fd791-desktop_recording1=GUID-E2832BE1-2A16-4EA1-9057-8C33A622FCDE=1=en=Default](/images/e2fd791-desktop_recording1=GUID-E2832BE1-2A16-4EA1-9057-8C33A622FCDE=1=en=Default.png)

![6d83298-web_reccording1=GUID-302AF676-25E9-4631-8D14-BCE4022A147B=1=en=Default](/images/6d83298-web_reccording1=GUID-302AF676-25E9-4631-8D14-BCE4022A147B=1=en=Default.png)

These single actions enable you to open an app or browser, as well as close them, by pointing and clicking them.

The activities generated using the desktop and web manual recorders contain partial selectors and containers (first screenshot), while the activities generated by the basic recorder contains a full selector and no container (third screenshot), just like with the automatic recording. More information about selectors is available in the About Selectors page.

![63c327c-Withselector=GUID-7AD21989-0210-45A3-B5CD-628CF5411B68=1=en=Default](/images/63c327c-Withselector=GUID-7AD21989-0210-45A3-B5CD-628CF5411B68=1=en=Default.png)

The partial selector for the example's Click activity:

![d0be13b-Selector=GUID-256A9DA9-DB67-46E9-AD0C-4FD20DC9B461=1=en=Default](/images/d0be13b-Selector=GUID-256A9DA9-DB67-46E9-AD0C-4FD20DC9B461=1=en=Default.png)

![43d644c-image_129=GUID-2D406BB8-3012-4F7C-A9C0-05BD1AACA144=1=en=Default](/images/43d644c-image_129=GUID-2D406BB8-3012-4F7C-A9C0-05BD1AACA144=1=en=Default.png)

# Click

![07c0873-basic_recording1=GUID-8C126E64-A4E0-45BC-9BB1-F9B6C7EA8D3B=1=en=Default](/images/07c0873-basic_recording1=GUID-8C126E64-A4E0-45BC-9BB1-F9B6C7EA8D3B=1=en=Default.png)

These types of actions enable you to record clicks on the desktop or a running application, select an option from a drop-down list or combo box, and select a check box or a radio button.

# Type

![71c1f6d-web_recording1=GUID-6EFCD680-1D08-4F66-9BEE-3B976D823DCD=1=en=Default](/images/71c1f6d-web_recording1=GUID-6EFCD680-1D08-4F66-9BEE-3B976D823DCD=1=en=Default.png)

These single actions include those that require input from the keyboard, such as keyboard shortcuts and key presses. To achieve this, two pop-up windows are used to retrieve your keyboard input.

![d22c212-image_132=GUID-9519DAC7-DEA2-4223-9193-C62B4C8B6545=1=en=Default](/images/d22c212-image_132=GUID-9519DAC7-DEA2-4223-9193-C62B4C8B6545=1=en=Default.png)

![b6c5099-image_133=GUID-F2C98EB5-CF3F-4C11-B3D7-33B01BC745C3=1=en=Default](/images/b6c5099-image_133=GUID-F2C98EB5-CF3F-4C11-B3D7-33B01BC745C3=1=en=Default.png)

# Copy

![cc3aab5-desktop_recording2=GUID-ECB6766C-98A9-46E8-A21E-B381F7DF10AF=1=en=Default](/images/cc3aab5-desktop_recording2=GUID-ECB6766C-98A9-46E8-A21E-B381F7DF10AF=1=en=Default.png)

![0e015c9-web_recording2=GUID-A121FC26-8323-435F-8372-EFCD9E31CF04=1=en=Default](/images/0e015c9-web_recording2=GUID-A121FC26-8323-435F-8372-EFCD9E31CF04=1=en=Default.png)

These actions enable you to copy a selected text from an opened application or web browser, so that you can use it later in the project. Screen scraping is also available under the Copy menu, as it enables you to extract images and text from an app or browser.

For more information, see Screen Scraping.

# Mouse Element

![1b21a3e-desktop_recording3=GUID-7A78A919-C68E-4EDE-A3F5-ACF71C6FB0B1=1=en=Default](/images/1b21a3e-desktop_recording3=GUID-7A78A919-C68E-4EDE-A3F5-ACF71C6FB0B1=1=en=Default.png)

These types of actions enable you to simulate mouse movements that cannot be recorded but give you access to more functionalities, such as right-clicking, hovering or double-clicking.

# Find Element

![7dda761-web_recording3=GUID-2C64BEFF-7F37-4003-85F2-0B2383D8461D=1=en=Default](/images/7dda761-web_recording3=GUID-2C64BEFF-7F37-4003-85F2-0B2383D8461D=1=en=Default.png)

These types of single actions enable you to identify specific UI elements or pause the automation until a particular window closes or an UI element is no longer displayed. The find relative element action is useful with apps that do not allow direct interaction with UI elements, such as Citrix.

# Window Element

![009117e-web_recording4=GUID-0360D1AE-8A12-4DF3-A597-131E8FE9BA1D=1=en=Default](/images/009117e-web_recording4=GUID-0360D1AE-8A12-4DF3-A597-131E8FE9BA1D=1=en=Default.png)

Window element actions enable you to close windows. Studio does this by hooking in the operating system to make sure the application is closed.

# Text

![e44ef19-web_recording5=GUID-BB1BD3B2-3539-4E97-8761-F9FF84B11D2A=1=en=Default](/images/e44ef19-web_recording5=GUID-BB1BD3B2-3539-4E97-8761-F9FF84B11D2A=1=en=Default.png)

Text single actions enable you to select or hover over text to make tooltips visible for scraping, right-click to make the context menu visible, copy and paste text and many others.

# Image

![459a763-desktop_recording4=GUID-57D055CA-D9B7-4B03-911C-EBD7882A7C48=1=en=Default](/images/459a763-desktop_recording4=GUID-57D055CA-D9B7-4B03-911C-EBD7882A7C48=1=en=Default.png)

Image single actions enable you to wait for a specified image to disappear, to find a specific image in an app or website, right-click or hover over an image and others. This type of manual recording can be useful with UI elements that are saved as graphics, as they cannot be highlighted as normal fields or text.
